[package]
name = "crosslib-core"
version = "0.0.1"
authors = ["Ben Steadman <steadmanben1@gmail.com>"]
edition = "2018"
include = [
	"README.md",
	"src/**/*",
	"Cargo.toml"
]

[dependencies]
rand = "0.7"
uuid="0.8"
